---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/istioctl version --remote=false
      register: istio_test_output
    - debug:
        msg: '{{ istio_test_output.stdout }}'
