---
- name: download...
  become: yes
  become_user: root
  get_url:
    url: '{{istio_tgz_url}}'
    dest: /tmp/{{istio_tgz}}
    mode: 0644
- name: unarchive...
  become: yes
  become_user: root
  unarchive:
    src: /tmp/{{istio_tgz}}
    dest: '{{istio_parent_install_dir}}'
    creates: '{{istio_install_dir}}'
- name: link...
  become: yes
  become_user: root
  file:
    src: '{{istio_install_dir}}'
    dest: '{{istio_link_dir}}'
    state: link
- name: add to login shell path...
  become: yes
  become_user: root
  with_items:
    - f: istio.sh
      d: /etc/profile.d
  template:
    src: '{{item.f}}.j2'
    dest: '{{item.d}}/{{item.f}}'
    mode: '{{item.m|default("0644")}}'
